# Datos de entrenamiento


Se realizara las extraccion  del espectro de potencia y frecuencia de algunos audios y formarlos como dataframe

In [1]:
import pandas as pd
import numpy as np


In [29]:
import numpy as np

# Define the number of training samples
num_samples = 100

# Generate random signal values
signal_values = np.random.rand(num_samples)

# Generate random power spectra
power_spectra = np.random.rand(num_samples, 1025)


# Create the training data array
data = np.column_stack((signal_values, power_spectra))


print(data)

[[0.49714923 0.07071888 0.54228618 ... 0.9887735  0.89385675 0.54866582]
 [0.86640162 0.00908797 0.83868121 ... 0.32930103 0.25341589 0.67459169]
 [0.22443899 0.91123209 0.04695618 ... 0.14514768 0.97999136 0.30660133]
 ...
 [0.9789194  0.58411103 0.11682419 ... 0.81366277 0.72610172 0.69740001]
 [0.02698505 0.29918322 0.64496077 ... 0.846831   0.31892936 0.81337533]
 [0.78263018 0.20406589 0.96508075 ... 0.4043187  0.76979663 0.67339825]]
